### ISSUE TITLE
Long Term Deposits are possible but they shouldn't

### ISSUE THREAD

**Issue by gentoofreak** [HOdlcoin/HOdlcoin#102] opened 2017-08-17 11:01 UTC
Using Wallet 3.0.1 I was able to deposit HODL for far more than a year.

It happened some weeks ago when I entered `170` into the date-value-field and forgot to choose `Days` in the dropdown and left it at `Months`. Well, yeah, I entered my wallet password etc. and now I have a HOdling unitl 2032/02/20.

Happend a second time some days ago, now I have another HOdling until 2029/04/10.

While I'm fine with the fact that some of my HOdl will remain unavailable to me for a long time (growing from 400 HODL to 623 HODL in 15 years), I find it confusing that the website says "max 1 year" and even the network itself accepted my deposits.

**Comment by ghobson2013** [comment] 2017-08-17 16:43
Hi, we are aware of this issue.
duplicate of https://github.com/HOdlcoin/HOdlcoin/issues/25

**Closed** 2017-12-14 22:06 UTC
