### ISSUE TITLE
Matured Coins not available

### ISSUE THREAD

**Issue by aparohde** [HOdlcoin/HOdlcoin#131] opened 2018-06-18 19:34 UTC
### System
Debian 9.4 64 bit
Wallet 3.0.2 64bit
----
### Description of issue
Coins matured and will be shown in HOdlings and matured.
Terms(Days) running negative. But matured coins are not available.
See screenshot. 
This Problem didn't happen on all deposits oder mined coins.

![screenshot_20180618_212319](https://user-images.githubusercontent.com/40369250/41557495-2aac7630-733e-11e8-9027-3e12f3e4adb4.png)
----

### Steps to reproduce
1. Deposit or mine coins
2. Wait until the coins are matured
3. The problem happens just for some deposits/minings. Not at all.
4. Deleting all files (and databases) and reinitialize didn't help.

**Comment by ghobson2013** [comment] 2018-06-18 21:52
hi
1 - setting up a term deposit for a term < 2 days yield 0 interest , so not sure what is the purpose of locking for 2 blocks.
2 - when a term deposit matures, you have to go to coin control select the inputs matching the matured amount and send it to yourself to clear the hodling table. ( they dont auto-remove )
3 - reinit wouldnt work if the issue is stale transations in the wallet.dat , the only way to clean that up is to use the startup flags -rescan -zapwallettxes=2   ( this will rescan the blockchain for your transactions ).
I would only do this if step 2 fails.

**Comment by aparohde** [comment] 2018-06-18 22:45
Hi and thank you for your answer.
I've never blocked any coin for two blocks.
The deposit-block is changing (I have noticed that only now). see new shot.
The 50 coins Principal mostly from mining with hodl-client. I'm using hodl for more than 20 month. It's the first time this problem appears.
 All deposits are made to my address and more than one month (mostly one year). 
Deleting all files means ALL files included wallet.dat dump and import private-keys.
![screenshot_20180619_003916](https://user-images.githubusercontent.com/40369250/41565997-ad113cb2-7359-11e8-90df-2ba6e71d958e.png)

**Comment by ghobson2013** [comment] 2018-06-19 05:33
hi
can you provide me your receive key public addresses so i can check the block explorer?
is the time on your client syncronized via ntp ? in other words is it possible your time is ahead of real time?
do you have a debug log i can look at from when you did the import ?

**Comment by ghobson2013** [comment] 2018-06-29 05:37
since i have not seen any additional info to troubleshoot this i will close this issue.

**Closed by ghobson2013** 2018-06-29 05:37 UTC
